### ISSUE TITLE
Has the PyTorch code been updated?

### ISSUE THREAD

**Issue by zhubingerdai** [axelBarroso/Key.Net-Pytorch#3]
Is this the full pytorch version?

**Comment by axelBarroso** [comment]
Hi, 

We have uploaded the inference code. The training code will be uploaded soon.

**Comment by zhubingerdai** [comment]
Thanks for your reply and look forward to your code！
















At 2022-01-03 05:25:32, "Axel Barroso" ***@***.***> wrote:

Hi,

We have uploaded the inference code. The training code will be uploaded soon.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
