### ISSUE TITLE
Any reason to need to calculate gradients in extract_kpts_dsc.py?

### ISSUE THREAD

**Issue by Miguel33Angel** [axelBarroso/Key.Net-Pytorch#8]
In the file extract_kpts_dsc.py, the gradient is calculated even when only doing inference, when, as far as I know, there's no need for it
Is there any reason why I shouldn't just include the line ` torch.set_grad_enabled(False)` ?

CUDA complains on not enough memory if I don't inlcude it, as I have a low memory graphics card (Nvidia 1650 RTX 4GB)

**Comment by axelBarroso** [comment]
Hello,

Thank you for your interest in our work!

Yes, you can remove the gradients calculation during inference, it should not change the local features detected by networks.

All the best,
Axel
